# Análise Exploratória de Dado (EDA)

In [26]:
# Bibliotecas necessárias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
# Importação dos dados
caminho_dados = '../data/raw/bq_2022.csv'
df = pd.read_csv(caminho_dados, delimiter=',', low_memory=False)

In [28]:
print("\n--- Primeiras linhas do Dataframe ---")
df.head()

--- Primeiras linhas do Dataframe ---

,id_municipio,nome_municipio,sigla_uf,cor_raca,populacao_homens,populacao_mulheres,populacao_total
0,1100015,Alta Floresta D'Oeste,RO,Amarela,1654,1544,3198
1,1100015,Alta Floresta D'Oeste,RO,Branca,1654,1544,3198
2,1100015,Alta Floresta D'Oeste,RO,Indígena,1654,1544,3198
3,1100015,Alta Floresta D'Oeste,RO,Parda,1654,1544,3198
4,1100015,Alta Floresta D'Oeste,RO,Preta,1654,1544,3198

In [29]:
print("\n--- Informações das Colunas ---")
df.info()

--- Informações das Colunas ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27850 entries, 0 to 27849
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_municipio        27850 non-null  int64
 1   nome_municipio      27850 non-null  object
 2   sigla_uf            27850 non-null  object
 3   cor_raca            27850 non-null  object
 4   populacao_homens    27850 non-null  int64
 5   populacao_mulheres  27850 non-null  int64
 6   populacao_total     27850 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.5+ MB

In [30]:
if 'df' in locals():
    # 4. Verificar a quantidade de dados faltantes por coluna
    print("\n--- Contagem de Dados Faltantes (NaN) por Coluna ---")
    dados_faltantes = df.isnull().sum()
    
    if dados_faltantes.sum() == 0:
        print("Não há dados faltantes no DataFrame.")
    else:
        print(dados_faltantes[dados_faltantes > 0])

--- Contagem de Dados Faltantes (NaN) por Coluna ---
Não há dados faltantes no DataFrame.

In [31]:
print("\n--- Descrição dos Dados Numéricos ---")
df.describe()

--- Descrição dos Dados Numéricos ---

       id_municipio  populacao_homens  populacao_mulheres  populacao_total
count  2.785000e+04      27850.000000        27850.000000     2.785000e+04
mean   3.253591e+06       2708.226391         2649.476481     5.357703e+03
std    9.848396e+05      14394.582714        14192.130555     2.858553e+04
min    1.100015e+06         48.000000           37.000000     8.900000e+01
25%    2.512101e+06        376.000000          350.000000     7.300000e+02
50%    3.146280e+06        852.500000          812.000000     1.662500e+03
75%    4.119202e+06       1922.000000         1857.000000     3.766000e+03
max    5.300108e+06     792426.000000       773500.000000     1.565926e+06

In [32]:
# Importação dos dados
caminho_dados = '../data/raw/alfabetizacao_2010.csv'
df2 = pd.read_csv(caminho_dados, delimiter=',', low_memory=False)

In [33]:
print("\n--- Primeiras linhas do Dataframe ---")
df2.head()

--- Primeiras linhas do Dataframe ---

         id_municipio                   municipio   ano   sexo  valor
0  Município (Código)                   Município   Ano   Sexo    NaN
1             1100015  Alta Floresta D'Oeste - RO  2010  Total   89.3
2             1100023              Ariquemes - RO  2010  Total   92.8
3             1100031                 Cabixi - RO  2010  Total   87.8
4             1100049                 Cacoal - RO  2010  Total   92.5

In [34]:
print("\n--- Informações das Colunas ---")
df2.info()

--- Informações das Colunas ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5566 entries, 0 to 5565
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_municipio  5566 non-null   object
 1   municipio     5566 non-null   object
 2   ano           5566 non-null   object
 3   sexo          5566 non-null   object
 4   valor         5565 non-null   float64
dtypes: float64(1), object(4)
memory usage: 217.6+ KB

In [35]:
if 'df2' in locals():
    # 4. Verificar a quantidade de dados faltantes por coluna
    print("\n--- Contagem de Dados Faltantes (NaN) por Coluna ---")
    dados_faltantes = df2.isnull().sum()
    
    if dados_faltantes.sum() == 0:
        print("Não há dados faltantes no DataFrame.")
    else:
        print(dados_faltantes[dados_faltantes > 0])

--- Contagem de Dados Faltantes (NaN) por Coluna ---
valor    1
dtype: int64

In [36]:
print("\n--- Descrição dos Dados Numéricos ---")
df2.describe()

--- Descrição dos Dados Numéricos ---

             valor
count  5565.000000
mean     85.258922
std       8.936029
min      58.400000
25%      77.900000
50%      88.100000
75%      92.500000
max      99.100000