# Análise Exploratória de Dado (EDA)

In [1]:
# Bibliotecas necessárias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Importação dos dados
caminho_dados = '../data/raw/bq_2022.csv'
df = pd.read_csv(caminho_dados, delimiter=',', low_memory=False)

In [3]:
print("\n--- Primeiras linhas do Dataframe ---")
df.head()

--- Primeiras linhas do Dataframe ---

,id_municipio,nome_municipio,sigla_uf,cor_raca,populacao_homens,populacao_mulheres,populacao_total
0,1100015,Alta Floresta D'Oeste,RO,Amarela,1654,1544,3198
1,1100015,Alta Floresta D'Oeste,RO,Branca,1654,1544,3198
2,1100015,Alta Floresta D'Oeste,RO,Indígena,1654,1544,3198
3,1100015,Alta Floresta D'Oeste,RO,Parda,1654,1544,3198
4,1100015,Alta Floresta D'Oeste,RO,Preta,1654,1544,3198

In [4]:
print("\n--- Informações das Colunas ---")
df.info()

--- Informações das Colunas ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27850 entries, 0 to 27849
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_municipio        27850 non-null  int64
 1   nome_municipio      27850 non-null  object
 2   sigla_uf            27850 non-null  object
 3   cor_raca            27850 non-null  object
 4   populacao_homens    27850 non-null  int64
 5   populacao_mulheres  27850 non-null  int64
 6   populacao_total     27850 non-null  int64
dtypes: int64(4), object(3)
memory usage: 1.5+ MB

In [ ]:
if 'df' in locals():
    # 4. Verificar a quantidade de dados faltantes por coluna
    print("\n--- Contagem de Dados Faltantes (NaN) por Coluna ---")
    dados_faltantes = df.isnull().sum()
    
    if dados_faltantes.sum() == 0:
        print("Não há dados faltantes no DataFrame.")
    else:
        print(dados_faltantes[dados_faltantes > 0])

--- Contagem de Dados Faltantes (NaN) por Coluna ---
Não há dados faltantes no DataFrame.

In [6]:
print("\n--- Descrição dos Dados Numéricos ---")
df.describe()

--- Descrição dos Dados Numéricos ---

       id_municipio  populacao_homens  populacao_mulheres  populacao_total
count  2.785000e+04      27850.000000        27850.000000     2.785000e+04
mean   3.253591e+06       2708.226391         2649.476481     5.357703e+03
std    9.848396e+05      14394.582714        14192.130555     2.858553e+04
min    1.100015e+06         48.000000           37.000000     8.900000e+01
25%    2.512101e+06        376.000000          350.000000     7.300000e+02
50%    3.146280e+06        852.500000          812.000000     1.662500e+03
75%    4.119202e+06       1922.000000         1857.000000     3.766000e+03
max    5.300108e+06     792426.000000       773500.000000     1.565926e+06

In [7]:
# Importação dos dados
caminho_dados = '../data/raw/alfabetizacao_2010.csv'
df2 = pd.read_csv(caminho_dados, delimiter=',', low_memory=False)

In [8]:
print("\n--- Primeiras linhas do Dataframe ---")
df2.head()

--- Primeiras linhas do Dataframe ---

         id_municipio                   municipio   ano   sexo  valor
0  Município (Código)                   Município   Ano   Sexo    NaN
1             1100015  Alta Floresta D'Oeste - RO  2010  Total   89.3
2             1100023              Ariquemes - RO  2010  Total   92.8
3             1100031                 Cabixi - RO  2010  Total   87.8
4             1100049                 Cacoal - RO  2010  Total   92.5

In [9]:
print("\n--- Informações das Colunas ---")
df2.info()

--- Informações das Colunas ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5566 entries, 0 to 5565
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_municipio  5566 non-null   object
 1   municipio     5566 non-null   object
 2   ano           5566 non-null   object
 3   sexo          5566 non-null   object
 4   valor         5565 non-null   float64
dtypes: float64(1), object(4)
memory usage: 217.6+ KB

In [10]:
if 'df2' in locals():
    # 4. Verificar a quantidade de dados faltantes por coluna
    print("\n--- Contagem de Dados Faltantes (NaN) por Coluna ---")
    dados_faltantes = df2.isnull().sum()
    
    if dados_faltantes.sum() == 0:
        print("Não há dados faltantes no DataFrame.")
    else:
        print(dados_faltantes[dados_faltantes > 0])

--- Contagem de Dados Faltantes (NaN) por Coluna ---
valor    1
dtype: int64

In [11]:
print("\n--- Descrição dos Dados Numéricos ---")
df2.describe()

--- Descrição dos Dados Numéricos ---

             valor
count  5565.000000
mean     85.258922
std       8.936029
min      58.400000
25%      77.900000
50%      88.100000
75%      92.500000
max      99.100000

In [12]:
caminho_dados = '../data/trusted/inep_MicrodadosEducaBasica2022.parquet'
df3 = pd.read_parquet(caminho_dados)

In [13]:
print("\n--- Primeiras linhas do Dataframe ---")
df3.head()

--- Primeiras linhas do Dataframe ---

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,QT_MAT_BAS,QT_MAT_INF,...,QT_MAT_ESP_CC,QT_MAT_ESP_CE,QT_MAT_BAS_FEM,QT_MAT_BAS_MASC,QT_MAT_BAS_ND,QT_MAT_BAS_BRANCA,QT_MAT_BAS_PRETA,QT_MAT_BAS_PARDA,QT_MAT_BAS_AMARELA,QT_MAT_BAS_INDIGENA
0,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,6.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,6.0
1,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,200.0,0.0,...,3.0,0.0,114.0,86.0,0.0,53.0,5.0,132.0,0.0,10.0
2,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,9.0,0.0,...,0.0,0.0,4.0,5.0,0.0,3.0,0.0,6.0,0.0,0.0
3,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,118.0,17.0,...,1.0,0.0,53.0,65.0,13.0,15.0,6.0,62.0,0.0,22.0
4,2022,Norte,1,Rondônia,RO,11,Alta Floresta D'Oeste,1100015,161.0,18.0,...,3.0,0.0,76.0,85.0,9.0,59.0,2.0,91.0,0.0,0.0

In [17]:
print("\n--- Informações das Colunas ---")
df3.info()

--- Informações das Colunas ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224649 entries, 0 to 224648
Data columns (total 32 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   NU_ANO_CENSO         224649 non-null  int64
 1   NO_REGIAO            224649 non-null  object
 2   CO_REGIAO            224649 non-null  int64
 3   NO_UF                224649 non-null  object
 4   SG_UF                224649 non-null  object
 5   CO_UF                224649 non-null  int64
 6   NO_MUNICIPIO         224649 non-null  object
 7   CO_MUNICIPIO         224649 non-null  int64
 8   QT_MAT_BAS           178346 non-null  float64
 9   QT_MAT_INF           178346 non-null  float64
 10  QT_MAT_INF_CRE       178346 non-null  float64
 11  QT_MAT_INF_PRE       178346 non-null  float64
 12  QT_MAT_FUND          178346 non-null  float64
 13  QT_MAT_FUND_AI       178346 non-null  float64
 14  QT_MAT_FUND_AF       178346 non-null  float64
 15  QT_MAT_MED           178346 non-null  float64
 16  QT_MAT_PROF          178346 non-null  float64
 17  QT_MAT_PROF_TEC      178346 non-null  float64
 18  QT_MAT_EJA           178346 non-null  float64
 19  QT_MAT_EJA_FUND      178346 non-null  float64
 20  QT_MAT_EJA_MED       178346 non-null  float64
 21  QT_MAT_ESP           178346 non-null  float64
 22  QT_MAT_ESP_CC        178346 non-null  float64
 23  QT_MAT_ESP_CE        178346 non-null  float64
 24  QT_MAT_BAS_FEM       178346 non-null  float64
 25  QT_MAT_BAS_MASC      178346 non-null  float64
 26  QT_MAT_BAS_ND        178346 non-null  float64
 27  QT_MAT_BAS_BRANCA    178346 non-null  float64
 28  QT_MAT_BAS_PRETA     178346 non-null  float64
 29  QT_MAT_BAS_PARDA     178346 non-null  float64
 30  QT_MAT_BAS_AMARELA   178346 non-null  float64
 31  QT_MAT_BAS_INDIGENA  178346 non-null  float64
dtypes: float64(24), int64(4), object(4)
memory usage: 54.8+ MB

In [18]:
if 'df3' in locals():
    # 4. Verificar a quantidade de dados faltantes por coluna
    print("\n--- Contagem de Dados Faltantes (NaN) por Coluna ---")
    dados_faltantes = df3.isnull().sum()
    
    if dados_faltantes.sum() == 0:
        print("Não há dados faltantes no DataFrame.")
    else:
        print(dados_faltantes[dados_faltantes > 0])

--- Contagem de Dados Faltantes (NaN) por Coluna ---
QT_MAT_BAS             46303
QT_MAT_INF             46303
QT_MAT_INF_CRE         46303
QT_MAT_INF_PRE         46303
QT_MAT_FUND            46303
QT_MAT_FUND_AI         46303
QT_MAT_FUND_AF         46303
QT_MAT_MED             46303
QT_MAT_PROF            46303
QT_MAT_PROF_TEC        46303
QT_MAT_EJA             46303
QT_MAT_EJA_FUND        46303
QT_MAT_EJA_MED         46303
QT_MAT_ESP             46303
QT_MAT_ESP_CC          46303
QT_MAT_ESP_CE          46303
QT_MAT_BAS_FEM         46303
QT_MAT_BAS_MASC        46303
QT_MAT_BAS_ND          46303
QT_MAT_BAS_BRANCA      46303
QT_MAT_BAS_PRETA       46303
QT_MAT_BAS_PARDA       46303
QT_MAT_BAS_AMARELA     46303
QT_MAT_BAS_INDIGENA    46303
dtype: int64

In [19]:
print("\n--- Descrição dos Dados Numéricos ---")
df3.describe()

--- Descrição dos Dados Numéricos ---

,NU_ANO_CENSO,CO_REGIAO,CO_UF,CO_MUNICIPIO,QT_MAT_BAS,QT_MAT_INF,QT_MAT_INF_CRE,QT_MAT_INF_PRE,QT_MAT_FUND,QT_MAT_FUND_AI,...,QT_MAT_ESP_CC,QT_MAT_ESP_CE,QT_MAT_BAS_FEM,QT_MAT_BAS_MASC,QT_MAT_BAS_ND,QT_MAT_BAS_BRANCA,QT_MAT_BAS_PRETA,QT_MAT_BAS_PARDA,QT_MAT_BAS_AMARELA,QT_MAT_BAS_INDIGENA
count,224649.0,224649.000000,224649.000000,2.246490e+05,178346.000000,178346.000000,178346.000000,178346.000000,178346.000000,178346.000000,...,178346.000000,178346.000000,178346.000000,178346.000000,178346.000000,178346.000000,178346.000000,178346.000000,178346.000000,178346.000000
mean,2022.0,2.647040,30.259347,3.041188e+06,265.675003,50.624987,22.067717,28.557271,148.319716,81.599980,...,7.698435,0.868026,131.234667,134.440335,73.142207,84.816609,8.927366,95.915008,0.888262,1.985551
std,0.0,1.022897,9.447640,9.484777e+05,340.902822,80.811453,45.544017,55.220702,217.763543,140.879046,...,12.185872,10.286391,174.495630,170.734582,135.909944,168.125623,23.303658,150.230566,5.049760,19.123825
min,2022.0,1.000000,11.000000,1.100015e+06,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2022.0,2.000000,23.000000,2.313005e+06,67.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,32.000000,34.000000,6.000000,6.000000,0.000000,11.000000,0.000000,0.000000
50%,2022.0,3.000000,31.000000,3.112604e+06,160.000000,15.000000,0.000000,5.000000,47.000000,16.000000,...,3.000000,0.000000,78.000000,82.000000,27.000000,32.000000,2.000000,40.000000,0.000000,0.000000
75%,2022.0,3.000000,35.000000,3.547304e+06,353.000000,71.000000,22.000000,34.000000,221.000000,102.000000,...,10.000000,0.000000,173.000000,179.000000,86.000000,99.000000,8.000000,120.000000,1.000000,0.000000
max,2022.0,5.000000,53.000000,5.300108e+06,40174.000000,2314.000000,2314.000000,1216.000000,4032.000000,2089.000000,...,534.000000,547.000000,23535.000000,23825.000000,18330.000000,34485.000000,2771.000000,14305.000000,600.000000,1325.000000